### ISSUE TITLE
dependencies installing error

### ISSUE THREAD

**Issue by tingyang01** [xchainjs/xchainpy-lib#83]
Hello,
I am installing this library like this on python 3.6.
pip3 install -r requirements.txt

I am getting this error after about 15 hours from starting the installation of this lib.
INFO: pip is looking at multiple versions of multidict to determine which version is compatible with other requirements. This could take a while.
Collecting multidict<7.0,>=4.5
  Using cached multidict-5.0.2-cp36-cp36m-manylinux2014_x86_64.whl (141 kB)
  Using cached multidict-5.0.1-cp36-cp36m-manylinux2014_x86_64.whl (141 kB)
  Using cached multidict-5.0.0-cp36-cp36m-manylinux2014_x86_64.whl (141 kB)
  Using cached multidict-4.7.6-cp36-cp36m-manylinux1_x86_64.whl (148 kB)
  Using cached multidict-4.7.5-cp36-cp36m-manylinux1_x86_64.whl (148 kB)
  Using cached multidict-4.7.4-cp36-cp36m-manylinux1_x86_64.whl (147 kB)
  Using cached multidict-4.7.3-cp36-cp36m-manylinux1_x86_64.whl (148 kB)
  Using cached multidict-4.7.2-cp36-cp36m-manylinux1_x86_64.whl (147 kB)
  Using cached multidict-4.7.1-cp36-cp36m-manylinux1_x86_64.whl (114 kB)
  Using cached multidict-4.7.0-cp36-cp36m-manylinux1_x86_64.whl (112 kB)
  Using cached multidict-4.6.1-cp36-cp36m-manylinux1_x86_64.whl (348 kB)
  Using cached multidict-4.6.0-cp36-cp36m-manylinux1_x86_64.whl (348 kB)
  Using cached multidict-4.5.2-cp36-cp36m-manylinux1_x86_64.whl (309 kB)
  Using cached multidict-4.5.1-cp36-cp36m-manylinux1_x86_64.whl (309 kB)
  Using cached multidict-4.5.0-cp36-cp36m-manylinux1_x86_64.whl (309 kB)

ERROR: Exception:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 317, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 364, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000

Let me know your idea for that,
Thanks

**Comment by Adelapt98** [comment]
hi, I suggest you install chains one by one.
for example at the first install Binance chain, bitcoin and ...
then if you get an error tell me.
because I don't know this error is related to which chain

**Comment by hoodieonwho** [comment]
marking this close as no reply was made
